# Generated by Django 4.2.2 on 2023-06-22 12:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditablePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_heading', models.CharField(max_length=50)),
                ('name_content', models.CharField(max_length=100)),
                ('occupation_heading', models.CharField(max_length=50)),
                ('occupation_content', models.CharField(max_length=100)),
                ('country_heading', models.CharField(max_length=50)),
                ('country_content', models.CharField(max_length=100)),
                ('image_img', models.ImageField(upload_to='my_images')),
                ('txt_over_img', models.CharField(max_length=50)),
            ],
        ),
    ]
